apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: tmc.kcp.io
spec:
  latestResourceSchemas:
  - v230711-a961437.apiresourceimports.apiresource.kcp.io
  - v230711-a961437.negotiatedapiresources.apiresource.kcp.io
  - v230618-0f88c5d.locations.scheduling.kcp.io
  - v230618-0f88c5d.placements.scheduling.kcp.io
  - v230618-0f88c5d.synctargets.workload.kcp.io
  permissionClaims:
  - group: ""
    resource: "namespaces"
    all: true
  - group: ""
    resource: "serviceaccounts"
    all: true
  - group: ""
    resource: "resourcequotas"
    all: true
  - group: ""
    resource: "events"
    all: true
  - group: ""
    resource: "configmaps"
    all: true
  - group: ""
    resource: "secrets"
    all: true
  - group: "events.k8s.io"
    resource: "events"
    all: true
  - group: "coordination.k8s.io"
    resource: "leases"
    all: true
  - group: "admissionregistration.k8s.io"
    resource: "mutatingwebhookconfigurations"
    all: true
  - group: "admissionregistration.k8s.io"
    resource: "validatingwebhookconfigurations"
    all: true
  - group: "admissionregistration.k8s.io"
    resource: "validatingadmissionpolicies"
    all: true
  - group: "admissionregistration.k8s.io"
    resource: "validatingadmissionpolicybindings"
    all: true
  - group: "certificates.k8s.io"
    resource: "certificatesigningrequests"
    all: true
  - group: "core.kcp.io"
    resource: "shards"
    identityHash: "82308c7d3146eed072bd6f8d075ad83075262f73555617f03cc0e798c4c99b7d"
    all: true
  - group: "apiextensions.k8s.io"
    resource: "customresourcedefinitions"
    all: true
  - group: "core.kcp.io"
    resource: "logicalclusters"
    identityHash: "82308c7d3146eed072bd6f8d075ad83075262f73555617f03cc0e798c4c99b7d"
    all: true
  - group: "rbac.authorization.k8s.io"
    resource: "roles"
    all: true
  - group: "rbac.authorization.k8s.io"
    resource: "clusterroles"
    all: true
  - group: "rbac.authorization.k8s.io"
    resource: "rolebindings"
    all: true
  - group: "rbac.authorization.k8s.io"
    resource: "clusterrolebindings"
    all: true
  - group: "apis.kcp.io"
    resource: "apiexports"
    all: true
  - group: "apis.kcp.io"
    resource: "apibindings"
    all: true
  - group: "apis.kcp.io"
    resource: "apiresourceschemas"
    all: true
  identity:
    secretRef:
      name: tmc-identity
      namespace: default
status: {}
