apiVersion: apis.kcp.io/v1alpha1
kind: APIBinding
metadata:
  name: tmc.kcp.io
spec:
  reference:
    export:
      name: tmc.kcp.io
      path: root:tmc
  permissionClaims:
  - group: "apis.kcp.io"
    resource: "apibindings"
    state: Accepted
    all: true
  - group: ""
    resource: "namespaces"
    state: Accepted
    all: true
  - group: "core.kcp.io"
    resource: "shards"
    identityHash: "d22f1749e9c3524f15755a0d342cc380a237e44214283ce6cf88a140924da93f"
    state: Accepted
    all: true
  - group: "apiextensions.k8s.io"
    resource: "customresourcedefinitions"
    state: Accepted
    all: true
  - group: "core.kcp.io"
    resource: "logicalclusters"
    identityHash: "d22f1749e9c3524f15755a0d342cc380a237e44214283ce6cf88a140924da93f"
    state: Accepted
    all: true
  - group: "rbac.authorization.k8s.io"
    resource: "clusterroles"
    state: Accepted
    all: true
  - group: "rbac.authorization.k8s.io"
    resource: "clusterrolebindings"
    state: Accepted
    all: true
  - group: "apis.kcp.io"
    resource: "apiexports"
#     identityHash: "bb6ac319ead1e1ed66c7e438713d7a53c2a1d00e895d841453521ff969861b56"
    state: Accepted
    all: true
  - group: "apis.kcp.io"
    resource: "apibindings"
#     identityHash: "bb6ac319ead1e1ed66c7e438713d7a53c2a1d00e895d841453521ff969861b56"
    state: Accepted
    all: true
  - group: "apis.kcp.io"
    resource: "apiresourceschemas"
#     identityHash: "bb6ac319ead1e1ed66c7e438713d7a53c2a1d00e895d841453521ff969861b56"
    state: Accepted
    all: true