builds:
- id: "tmc"
  main: ./cmd/tmc
  binary: bin/tmc
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0
- id: "kubectl-workload"
  main: ./cmd/kubectl-workload
  binary: bin/kubectl-workload
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0
archives:
- id: tmc
  builds:
  - tmc
- id: kubectl-tmc-plugin
  builds:
  - kubectl-tmc
  - kubectl-workload
  name_template: "kubectl-tmc-plugin_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  files:
    - bin/kubectl-workloads
release:
  draft: true
  prerelease: auto
  mode: keep-existing
