apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:tmc:apiexport:scheduling:maximal-permission-policy
rules:
- apiGroups: ["scheduling.kcp.io"]
  verbs: ["*"]
  resources:
  - locations
  - placements
- apiGroups: ["scheduling.kcp.io"]
  verbs: ["get","list","watch"]
  resources:
  - locations/status
  - placements/status
