apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:tmc:apiexport:apiresource:maximal-permission-policy
rules:
- apiGroups: ["apiresource.kcp.io"]
  verbs: ["*"]
  resources:
  - apiresourceimports
  - negotiatedapiresources
- apiGroups: ["apiresource.kcp.io"]
  verbs: ["get","list","watch"]
  resources:
  - apiresourceimports/status
  - negotiatedapiresources/status
