apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:tmc:apiexport:kcp-admin:maximal-permission-policy
rules:
  - apiGroups: ["scheduling.kcp.io","workload.kcp.io"]
    verbs: ["*"]
    resources: ["*"]
